---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
He thought he saw an Elephant  
That practised on a fife:  
He looked again, and found it was  
A letter from his wife.  
'At length I realize,' he said,  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
He is said to have been the last Red Man  
In Acton. And the Miller is said to have laughed—  
If you like to call such a sound a laugh.  
But he gave no one else a laugher’s license.  
For he turned suddenly grave as if to say,  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
She say, "Do you love me?" I tell her, "Only partly"  
I only love my bed and my momma, I'm sorry  
Fifty Dub, I even got it tatted on me  
81, they'll bring the crashers to the party  
And you know me  
Turn the O2 into the O3, dog  
Without 40, Oli', there'd would be no me  
Imagine if I never met the broskies  